# Generated by Django 4.1.7 on 2023-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Home Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Home Subtitle')),
                ('btn_name_1', models.CharField(max_length=15, verbose_name='Home Button 1')),
                ('btn_name_2', models.CharField(max_length=15, verbose_name='Home Button 2')),
                ('text', models.CharField(max_length=40, verbose_name='Home Text')),
                ('btn_name_3', models.CharField(max_length=15, verbose_name='Home Button 3')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': 'Sidebar', 'verbose_name_plural': 'Sidebar'},
        ),
    ]
