# Generated by Django 4.1.7 on 2023-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_alter_sidebar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='About Image')),
                ('title', models.CharField(max_length=25, verbose_name='About Title')),
                ('text', models.TextField(verbose_name='About Text')),
                ('subtitle', models.CharField(max_length=30, verbose_name='About Subtitle')),
                ('discount', models.CharField(max_length=30, verbose_name='About Discount')),
                ('offer', models.CharField(max_length=40, verbose_name='About Offer')),
                ('promocode', models.CharField(max_length=30, verbose_name='About Promocode')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='About Content Image')),
                ('name', models.CharField(max_length=20, verbose_name='About Content Barber Name')),
                ('social', models.CharField(max_length=60, verbose_name='About Content Barber Social')),
                ('social_url', models.URLField(verbose_name='About Content Social Url')),
            ],
        ),
    ]
