# Generated by Django 4.1.7 on 2023-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_aboutcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='social_url',
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='social',
            field=models.TextField(verbose_name='About Content Barber Social'),
        ),
    ]
