# Generated by Django 4.1.7 on 2023-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_aboutcontent_social_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='social_url',
            field=models.CharField(default=1, max_length=300, verbose_name='About Content Social Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='social',
            field=models.CharField(max_length=60, verbose_name='About Content Barber Social'),
        ),
    ]
