# Generated by Django 4.1.7 on 2023-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutcontent_social_url_alter_aboutcontent_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Service Image')),
                ('title', models.CharField(max_length=20, verbose_name='Service Title')),
                ('price', models.CharField(max_length=15, verbose_name='Service Price')),
            ],
        ),
    ]
