# Generated by Django 4.1.7 on 2023-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicecontent_remove_service_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookaSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Book a Seat Title')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Book a Seat SubTitle')),
                ('btn_name', models.CharField(max_length=15, verbose_name='Book a Seat Button Name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Book a Seat Image')),
            ],
            options={
                'verbose_name': 'BookaSeat',
                'verbose_name_plural': 'BookaSeat',
            },
        ),
    ]
