# Generated by Django 4.1.7 on 2023-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookaseatcontact_alter_bookaseat_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookaseatcontact',
            name='user_count',
            field=models.PositiveIntegerField(default=1, verbose_name='User Count'),
            preserve_default=False,
        ),
    ]
