# Generated by Django 4.1.7 on 2023-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookaseatcontact_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaseatcontact',
            name='user_count',
            field=models.CharField(max_length=20, verbose_name='User Count'),
        ),
    ]
