# Generated by Django 4.1.7 on 2023-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bookaseatcontact_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Price List Title')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Price List SubTitle')),
                ('img', models.ImageField(upload_to='images', verbose_name='Price List Image')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25, verbose_name='Price List Version')),
                ('price', models.CharField(max_length=15, verbose_name='Price List Price')),
            ],
        ),
    ]
