# Generated by Django 4.1.7 on 2023-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pricelist_pricelistcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Contact Title')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Contact SubTitle')),
                ('phone_number', models.CharField(max_length=40, verbose_name='Contact Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('social', models.CharField(max_length=80, verbose_name='Contact Social')),
                ('day', models.CharField(max_length=20, verbose_name='Contact Day')),
                ('time', models.CharField(max_length=40, verbose_name='Contact Time')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'PriceList', 'verbose_name_plural': 'PriceList'},
        ),
    ]
