# Generated by Django 4.1.7 on 2023-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_alter_pricelist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Footer Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Footer Subtitle')),
                ('symbol', models.CharField(max_length=40, verbose_name='Footer Symbol')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Footer Content Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Footer Content SubTitle')),
            ],
        ),
    ]
