# Generated by Django 4.1.7 on 2023-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_footer_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Home Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='img2',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Home Image 2'),
            preserve_default=False,
        ),
    ]
